add restart command

diff --git a/bin/mcsm b/bin/mcsm
--- a/bin/mcsm
+++ b/bin/mcsm
@@ -252,6 +252,36 @@ mcsm_cmd_stop_all () {
 }
 
 
+mcsm_cmd_restart () {
+	servername=$1
+	if [ "$servername" == "" ]
+	then
+		echo "$cmd SERVERNAME"
+		exit 1
+	fi
+	
+	serverdir=`mcsm_func_validate_servername $servername`
+	if [ "$?" != "0" ]; then exit 1; fi
+
+	echo "Restarting ${servername}."
+
+	stopworked=`mcsm_cmd_stop $servername`
+	if [ "$?" != "0" ]
+	then
+		echo "Failed to stop ${servername}."
+		exit 1
+	fi
+
+	startworked=`mcsm_cmd_start $servername`
+	if [ "$?" != "0" ]
+	then
+		echo "Failed to start ${servername}."
+		exit 1
+	fi
+
+	exit 0
+}
+
 mcsm_cmd_status () {
 	SERVERS=`mcsm_func_server_args $*`
 	if [ "$?" != "0" ]; then exit 1; fi
@@ -384,6 +414,11 @@ then
 	else
 		mcsm_cmd_stop $*
 	fi
+fi
+
+if [ "$cmd" == "restart" ]
+then
+	mcsm_cmd_restart $*
 fi
 
 if [ "$cmd" == "status" ]
